# $FreeBSD$

MASTERDIR=	${.CURDIR}/../libresense-pkg-zabbix-proxy

PORTNAME=	libresense-pkg-zabbix-proxy6

CONFLICTS=	libresense-pkg-zabbix-proxy \
		libresense-pkg-zabbix-proxy4 \
		libresense-pkg-zabbix-proxy44 \
		libresense-pkg-zabbix-proxy5 \
		libresense-pkg-zabbix-proxy54 \
		libresense-pkg-zabbix-proxy62

RUN_DEPENDS=	zabbix_proxy:net-mgmt/zabbix6-proxy

ZABBIXINTERNALNAME=	zabbix-proxy6
ZABBIXTITLE=	Zabbix Proxy 6
ZABBIXVERSION=	6

.include "${MASTERDIR}/Makefile"
