# $FreeBSD$

MASTERDIR=	${.CURDIR}/../libresense-pkg-zabbix-proxy

PORTNAME=	libresense-pkg-zabbix-proxy54

CONFLICTS=	libresense-pkg-zabbix-proxy \
		libresense-pkg-zabbix-proxy4 \
		libresense-pkg-zabbix-proxy44 \
		libresense-pkg-zabbix-proxy5 \
		libresense-pkg-zabbix-proxy6 \
		libresense-pkg-zabbix-proxy62

RUN_DEPENDS=	zabbix_proxy:net-mgmt/zabbix54-proxy

ZABBIXINTERNALNAME=	zabbix-proxy54
ZABBIXTITLE=	Zabbix Proxy 5.4
ZABBIXVERSION=	54

.include "${MASTERDIR}/Makefile"
