# $FreeBSD$

MASTERDIR=	${.CURDIR}/../libresense-pkg-zabbix-proxy

PORTNAME=	libresense-pkg-zabbix-proxy4

CONFLICTS=	libresense-pkg-zabbix-proxy \
		libresense-pkg-zabbix-proxy44 \
		libresense-pkg-zabbix-proxy5 \
		libresense-pkg-zabbix-proxy54 \
		libresense-pkg-zabbix-proxy6 \
		libresense-pkg-zabbix-proxy62

RUN_DEPENDS=	zabbix_proxy:net-mgmt/zabbix4-proxy

ZABBIXINTERNALNAME=	zabbix-proxy4
ZABBIXTITLE=	Zabbix Proxy 4.0
ZABBIXVERSION=	40

.include "${MASTERDIR}/Makefile"
